export const FETCH_DISKS_START = 'FETCH_DISKS_START';
export const FETCH_DISKS_SUCCESS = 'FETCH_DISKS_SUCCESS';
export const FETCH_DISKS_FAIL = 'FETCH_DISKS_FAIL';

export const FETCH_DISK_START = 'FETCH_DISK_START';
export const FETCH_DISK_SUCCESS = 'FETCH_DISK_SUCCESS';
export const FETCH_DISK_FAIL = 'FETCH_DISK_FAIL';

export const FILTER_TEXT = 'FILTER_TEXT';

export const AUTH_CHECK_STATE = 'AUTH_CHECK_STATE';
export const AUTH_USER = 'AUTH_USER';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAIL = 'AUTH_FAIL';
export const AUTH_CHECK_TIMEOUT = 'AUTH_CHECK_TIMEOUT';
export const AUTH_INITIATE_LOGOUT = 'AUTH_INITIATE_LOGOUT';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
