export const FETCH_DISKS_START = 'FETCH_DISKS_START';
export const FETCH_DISKS_SUCCESS = 'FETCH_DISKS_SUCCESS';
export const FETCH_DISKS_FAIL = 'FETCH_DISKS_FAIL';

export const FETCH_DISK_START = 'FETCH_DISK_START';
export const FETCH_DISK_SUCCESS = 'FETCH_DISK_SUCCESS';
export const FETCH_DISK_FAIL = 'FETCH_DISK_FAIL';

export const FILTER_TEXT = 'FILTER_TEXT';
